### ISSUE TITLE
Consider using SPARQL syntax highlighter

### ISSUE THREAD

**Issue by jakubklimek** [payola/payola-viz#15]
Such as this one: http://codemirror.net/1/sparqltest.html or another one that can be easily added.

It would help here: http://live.payola.cz:29090/components#/detail/2

**Comment by jirihelmich** [comment]
transitive issue https://github.com/webjars/codemirror/issues/28

**Comment by jakubklimek** [comment]
Wow, fixed in 18 minutes :+1:
