### ISSUE TITLE
Discovery detail link not working

### ISSUE THREAD

**Issue by jakubklimek** [payola/payola-viz#27]
Discovery detail leads to e.g. http://ldvm.opendata.cz:29090/pipelines#/list/?discoveryId=3 but that still puts me on the pipeline list. I think I should see the discovery process log.

**Comment by jirihelmich** [comment]
It is meant to be a filter - it lists just pipelines from that discovery.

**Comment by jakubklimek** [comment]
Ok. The label details is misleading then. But we will see how it looks when there is more executions
