### ISSUE TITLE
Make Use Case 2 work

### ISSUE THREAD

**Issue by jakubklimek** [payola/payola-viz#28]
* Read UC2 in the paper
* see my latest commits to the repo
* ruian data source already added
* New analyzer: ldvm-a-ruian-obce.ttl - should be the one that extracts all "obce" from RUIAN - nested one
* New analyzer: ldvm-a-ruian-geocoder.ttl - 2 inputs, one from the previous analyzer, 2nd input will be connected to a datasource created from example-obce-ruian.ttl. Here, implementation is needed. Basically take all data from dataset input and pass it to output. Add for each entity with the "ruianlink:obec" property leading to RUIAN obec the s:geo of the "obec" from RUIAN input.
* Discovery will connect the ruian DS to the first input and then the previous analyzer after RUIAN input. The first choice will not work due to ruian size. The second one is the correct one. 
* Output should be consumable by GMap visualizer and 2 points should be shown.

**Comment by jirihelmich** [comment]
- added uploading DS from remote TTL
- fixed TTL defs https://github.com/payola/ldvm/commit/c856c9bdb4cff3ff6ca76b33cba6a907b4810f07
- fixed bugs in GMaps viz

**Comment by jirihelmich** [comment]
discovered

![image](https://cloud.githubusercontent.com/assets/174768/6648316/bb324b20-c9d8-11e4-9d59-6d48f3aaa4c6.png)

**Comment by jirihelmich** [comment]
Unlabelled is ldvm-a-ruian-obce.ttl

**Comment by jirihelmich** [comment]
http://ldvm.opendata.cz/resource/template/analyzer/ruian/geocoder
- has an invalid link to output data sample ttl

You said that it should add "ruianlink:obec" links, but that property is in one of its descriptors. I'm a bit confused.

**Comment by jirihelmich** [comment]
added support for combining DSs

**Comment by jakubklimek** [comment]
I must have forgotten about the data sample. Added, link fixed, component labeled.

No, I said to each entity that has the ruianlink:obec link (dataset linked to RUIAN) add s:geo s:Geocoordinates that is found in the RUAIN dataset with the entity to which ruianlink:obec leads

**Comment by jirihelmich** [comment]
![image](https://cloud.githubusercontent.com/assets/174768/6650653/64202d38-ca1f-11e4-8ee3-b7fdfd50acfc.png)

![image](https://cloud.githubusercontent.com/assets/174768/6650655/6be7b16c-ca1f-11e4-83c3-3f88c8c5792b.png)

![image](https://cloud.githubusercontent.com/assets/174768/6650657/7b769968-ca1f-11e4-9360-59eac644f6de.png)

![image](https://cloud.githubusercontent.com/assets/174768/6650678/056b30ac-ca20-11e4-880c-8b83416a618b.png)


This is what I get now, will investigate.

**Comment by jirihelmich** [comment]
```
Port <http://ldvm.opendata.cz/resource/template/analyzer/ruian/obce/input> compatibility with <http://payola.cz/resource/temporary/14f9b671-f771-4c18-963c-dd1cc1996cad#instance> result: false

Port <http://ldvm.opendata.cz/resource/template/analyzer/ruian/geocoder/input/ruian> compatibility with <http://payola.cz/resource/temporary/14f9b671-f771-4c18-963c-dd1cc1996cad#instance> result: false
```

ttl data in that temp storage:
```
@prefix ns0:	<http://purl.org/dc/terms/> .
@prefix ns1:	<http://linked.opendata.cz/resource/temp/> .
ns1:myplace	ns0:title	"My place" .
@prefix ns2:	<http://ruian.linked.opendata.cz/ontology/links/> .
ns1:myplace	ns2:obec	<http://ruian.linked.opendata.cz/resource/obce/554782> .
ns1:myplace2	ns0:title	"My place 2" ;
	ns2:obec	<http://ruian.linked.opendata.cz/resource/obce/563889> .
```

ASK:
```
prefix xsd:	<http://www.w3.org/2001/XMLSchema#> 
		prefix rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
		prefix skos:	<http://www.w3.org/2004/02/skos/core#> 
		prefix s:	<http://schema.org/> 
		prefix ogcgml:	<http://www.opengis.net/ont/gml#> 
		prefix ruian:	<http://ruian.linked.opendata.cz/ontology/> 
		prefix ruianlink: <http://ruian.linked.opendata.cz/ontology/links/> 
		ASK {
		?object	
			ruianlink:obec	?obec ;
			.
		}
```

OK, now it's clear...

```
Virtuoso 37000 Error SP030: SPARQL compiler, line 13: Dot immediately after semicolon is permitted in pure SPARQL but not in SPARQL-BI at '.' before '}'

SPARQL query:
define sql:big-data-const 0 
#output-format:text/html
define sql:signal-void-variables 1 define input:default-graph-uri <urn:75a520e0-9f30-4c6a-b7a0-91142bd03374> prefix xsd:	<http://www.w3.org/2001/XMLSchema#> 
		prefix rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
		prefix skos:	<http://www.w3.org/2004/02/skos/core#> 
		prefix s:	<http://schema.org/> 
		prefix ogcgml:	<http://www.opengis.net/ont/gml#> 
		prefix ruian:	<http://ruian.linked.opendata.cz/ontology/> 
		prefix ruianlink: <http://ruian.linked.opendata.cz/ontology/links/> 
		ASK {
		?object	
			ruianlink:obec	?obec ;
.
			
		}
```

**Comment by jirihelmich** [comment]
This one, I guees.

![image](https://cloud.githubusercontent.com/assets/174768/6651641/e5518628-ca4b-11e4-884d-56b5b5d9738d.png)

**Comment by jakubklimek** [comment]
Yep :-) now thw implementation :-)

**Comment by jirihelmich** [comment]
nice one ;-)

![image](https://cloud.githubusercontent.com/assets/174768/6653067/65f00f5c-ca83-11e4-85d9-71f4268b973d.png)
