### ISSUE TITLE
When starting with a file upload only pipelines containing the uploaded file should be offered

### ISSUE THREAD

**Issue by jakubklimek** [payola/payola-viz#36]
![image](https://cloud.githubusercontent.com/assets/718827/6655792/713ebd4c-cb0d-11e4-96ee-8e7e184833af.png)
Here it only uses RUIAN, not the uploaded file

**Comment by jirihelmich** [comment]
Those are no longer saved after the discovery is done.

![image](https://cloud.githubusercontent.com/assets/174768/6656043/832d1aaa-cb1a-11e4-989e-6bdcebf494ce.png)
