### ISSUE TITLE
Direct the edges in pipeline visualization, if easily possible

### ISSUE THREAD

**Issue by jakubklimek** [payola/payola-viz#38]
This is something a reviewer will definitely point out - that the visualization of the pipeline is incorrect due to undirected edges and confusing because of a missing tree layout. Consider this low prio, but nice to have.

**Comment by jirihelmich** [comment]
![image](https://cloud.githubusercontent.com/assets/174768/6655872/3feb4198-cb12-11e4-8e9a-55d1f30854dd.png)
